- name: Publiccode Parser Action
  # You may pin to the exact commit or the version.
  # uses: italia/publiccode-parser-action@5ba8d8b9c246d497535110175aaa0f6e5ef9cb21
  uses: italia/publiccode-parser-action@v0.0.3-alpha
  with:
    # publiccode.yml path
    publiccode: # default is publiccode.yml
    # publiccode.yml path
    comment-on-pr: # optional, default is false
